/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

/**
 *
 * @author secacad-sistemas
 */
public class FrmCitas extends javax.swing.JInternalFrame {

    /**
     * Creates new form Forma2
     */
    public FrmCitas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jtxtdetalleperro = new javax.swing.JTextField();
        jtxtPrecio = new javax.swing.JTextField();
        jcbxdnicli = new javax.swing.JComboBox<>();
        txtIdCita = new javax.swing.JTextField();
        jcbxveterinario = new javax.swing.JComboBox<>();
        jdchFechaReservacion = new com.toedter.calendar.JDateChooser();
        jdchFechaProgramada = new com.toedter.calendar.JDateChooser();
        btnRegistrar = new javax.swing.JButton();
        btnConsultarCita = new javax.swing.JButton();
        btnEliminarCita = new javax.swing.JButton();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(187, 187, 239)), "REGISTRO DE CITAS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 3, 24))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtdetalleperro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DETALLES DEL PERRO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel2.add(jtxtdetalleperro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 210, 130));

        jtxtPrecio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PRECIO DE RESERVA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel2.add(jtxtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 140, 60));

        jcbxdnicli.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DNI CLIENTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel2.add(jcbxdnicli, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 210, 60));

        txtIdCita.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ID CITA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel2.add(txtIdCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 210, 60));

        jcbxveterinario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "VETERINARIO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel2.add(jcbxveterinario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 280, 60));

        jdchFechaReservacion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FECHA DE RESERVACION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel2.add(jdchFechaReservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 200, 80));

        jdchFechaProgramada.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FECHA PROGRAMADA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel2.add(jdchFechaProgramada, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 220, 80));

        btnRegistrar.setBackground(new java.awt.Color(94, 133, 210));
        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 180, 50));

        btnConsultarCita.setBackground(new java.awt.Color(94, 133, 210));
        btnConsultarCita.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnConsultarCita.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultarCita.setText("CONSULTAR");
        btnConsultarCita.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(btnConsultarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 180, 50));

        btnEliminarCita.setBackground(new java.awt.Color(94, 133, 210));
        btnEliminarCita.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEliminarCita.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarCita.setText("ELIMINAR");
        btnEliminarCita.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(btnEliminarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 180, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnConsultarCita;
    public javax.swing.JButton btnEliminarCita;
    public javax.swing.JButton btnRegistrar;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JComboBox<String> jcbxdnicli;
    public javax.swing.JComboBox<String> jcbxveterinario;
    public com.toedter.calendar.JDateChooser jdchFechaProgramada;
    public com.toedter.calendar.JDateChooser jdchFechaReservacion;
    public javax.swing.JTextField jtxtPrecio;
    public javax.swing.JTextField jtxtdetalleperro;
    public javax.swing.JTextField txtIdCita;
    // End of variables declaration//GEN-END:variables
}
