/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

/**
 *
 * @author secacad-sistemas
 */
public class FrmProductos extends javax.swing.JInternalFrame {

    /**
     * Creates new form Forma2
     */
    public FrmProductos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtxtNombreProducto = new javax.swing.JTextField();
        txtIdProducto = new javax.swing.JTextField();
        jcbxCategoria = new javax.swing.JComboBox<>();
        jtxtCantidadProducto = new javax.swing.JTextField();
        jtxtPrecio = new javax.swing.JTextField();
        jdchFechaVencimiento = new com.toedter.calendar.JDateChooser();
        jspnStock = new javax.swing.JSpinner();
        btnRegistrar = new javax.swing.JButton();
        btnEliminarProducto = new javax.swing.JButton();
        btnConsultarProducto = new javax.swing.JButton();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(187, 187, 239)), "REGISTRO DE PRODUCTOS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 3, 24))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtNombreProducto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NOMBRE DE PRODUCTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel1.add(jtxtNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 320, 80));

        txtIdProducto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ID PRODUCTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel1.add(txtIdProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 110, 80));

        jcbxCategoria.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CATEGORIA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel1.add(jcbxCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 440, 80));

        jtxtCantidadProducto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CANTIDAD POR PRODUCTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel1.add(jtxtCantidadProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 210, 80));

        jtxtPrecio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PRECIO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel1.add(jtxtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 220, 80));

        jdchFechaVencimiento.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FECHA DE VENCIMIENTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel1.add(jdchFechaVencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 220, 70));

        jspnStock.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "STOCK", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel1.add(jspnStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 210, 70));

        btnRegistrar.setBackground(new java.awt.Color(94, 133, 210));
        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 180, 50));

        btnEliminarProducto.setBackground(new java.awt.Color(94, 133, 210));
        btnEliminarProducto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEliminarProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarProducto.setText("ELIMINAR");
        btnEliminarProducto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(btnEliminarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, 180, 50));

        btnConsultarProducto.setBackground(new java.awt.Color(94, 133, 210));
        btnConsultarProducto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnConsultarProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultarProducto.setText("CONSULTAR");
        btnConsultarProducto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnConsultarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarProductoActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 180, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnConsultarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarProductoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnConsultarProducto;
    public javax.swing.JButton btnEliminarProducto;
    public javax.swing.JButton btnRegistrar;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JComboBox<String> jcbxCategoria;
    public com.toedter.calendar.JDateChooser jdchFechaVencimiento;
    public javax.swing.JSpinner jspnStock;
    public javax.swing.JTextField jtxtCantidadProducto;
    public javax.swing.JTextField jtxtNombreProducto;
    public javax.swing.JTextField jtxtPrecio;
    public javax.swing.JTextField txtIdProducto;
    // End of variables declaration//GEN-END:variables
}
